name: 'Client SDK Test Report'
on:
  workflow_run:
    workflows: ['Build and Test Client SDK']                     # runs after CI workflow
    types:
      - completed
    branches: ['main', 'master']
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version:
          - '3.1.x'
          - '6.0.x'
          - '4.6.2'
    steps:
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        artifact: dotnet-client-results-${{ matrix.dotnet-version }}
        name: dotnet-client-results-${{ matrix.dotnet-version }}
        path: '*.trx'
        reporter: dotnet-trx